# =================================
# = Spring
# =================================
spring:
  datasource:
    url: jdbc:mysql://server-here:3306/realmeet?&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: admin