# =================================
# = Spring
# =================================
spring:
  datasource:
    url: jdbc:mysql://realmeet-db.cjdz8mocsswq.us-east-1.rds.amazonaws.com:3306/realmeet?&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: admin